name: Documentation update
description: Suggest updates to the documentation
title: "[DOCS] <title>"
labels: "type :: maintenance"
body:
    - type: textarea
      id: problem-related
      attributes:
          label: Is your documentation request related to a problem? Please describe
          description: A clear and concise description of what the problem is. Ex. I'm always frustrated when ...
      validations:
          required: false

    - type: textarea
      id: description
      attributes:
          label: Describe the update you'd like
          description: A clear and concise description of what you want to happen
      validations:
          required: true

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
      validations:
          required: false
