name: Feature Request
description: Suggest new features for the product
title: "[FEATURE] <title>"
labels: "type :: feature"
body:
    - type: textarea
      id: problem
      attributes:
          label: Problem Statement
          description: What is the issue being faced and needs addressing?
      validations:
          required: false

    - type: textarea
      id: benifit-who
      attributes:
          label: Who will benefit?
          description: Will this fix a problem that only one user has, or will it benefit a lot of people
      validations:
          required: true

    - type: textarea
      id: benifits-what
      attributes:
          label: What benefits does this bring?
      validations:
          required: true

    - type: textarea
      id: proposed-solution
      attributes:
          label: Proposed solution
          description: How would you like to see this issue resolved?
      validations:
          required: true

    - type: textarea
      id: examples
      attributes:
          label: Examples
          description: Are there any examples of this which exist in other software?
          value: N/A
      validations:
          required: true
